---
slug: application
---

# Plot Application

Please read the following before filling out the application form below.

## General Garden Details

The garden plots are behind the Emerald House property, 67 Davisville Road, East Falmouth. We hope to be able to support around 30-35 gardeners. Most beds will be standard plots measuring 10'x10' with no elevation above ground level. In addition we will have at least two raised beds (depending on demand and budget) for gardeners with limited mobility and at least one wheelchair accessible bed too. 

Water will be available approximately every 20-30' in the garden. The fence surrounding the garden will be 5' high 1 inch deerbuster hex fencing with 1' buried for critter control. We will have at least two access gates, one of which will be wheelchair accessible.

Plots will be $25 for the season, but you may request a waiver in your application if needed. Otherwise, you will be asked to send a check if you application is successful.

## Plot Applications

We are opening applications for garden plots on March 1 with **a deadline on March 21 at 11:59PM**

We do not know the level of demand we will experience, but if we have more applications that available plots we will allocate the plots in the following order:

1. Garden committee members and Emerald House occupants (expecting ~7 plots)
1. Three plots to families of Falmouth Public School students (we are committed to building a strong relationship with the school district and diversify the age of garden participants - please use form to indicate that you have children in the public schools)
1. One quarter of remaining plots to applicants with nearest physical addresses to garden (to ensure garden is visited regularly and supported locally)
1. Open lottery for remaining plots (probably ~15-20 plots depending on total final plot numbers)

Raised beds will be allocated within this system and wheelchair beds will be assigned based on interest and available space.

Applications are only open to Falmouth residents.

<iframe src = "https://docs.google.com/forms/d/e/1FAIpQLSdEB2hDHsqiMH6q8DtJtNqWHUNHcNNuiS9c5-8dvhrj1x9IJg/viewform?usp=sf_link" id="commentForm" width = "100%" height = 2500 frameBorder="0"></iframe>
