---
slug: history
title: History
---

> The Emerald family homestead on Davisville Road stands as one reminder of an extraordinary period in Falmouth's history. The late 1800s introduced an important new element to the community. The Portuguese culture was admirable and the agricultural vision of the new immigrants was remarkable. A century after the first immigration their descendants are vital contributors to the life of the town. Now that the town has bought the Emerald property, we have an opportunity to insure that future generations understand and appreciate this period of history

-- Richard Kendall

## Learn more

Here are some links to some articles about the history of the property and Portuguese community in Falmouth.

* [The Emerald Family of East Falmouth (PDF)](http://woodsholemuseum.org/oldpages/sprtsl/v12n1-Emerald.pdf) by Richard Kendall
* [Strawberry Farming (PDF)](http://woodsholemuseum.org/oldpages/sprtsl/v21n2-Strawberry.pdf) by Jenllifer Stolle Gaines (PDF)
* [Welcoming the Next Generation of Immigrants](https://www.capenews.net/falmouth/columns/troys-take-welcoming-the-next-generation-of-immigrants/article_07a1fb4a-a249-59f3-9bd8-8489719ccebf.html) by Troy Clarkson